# <font color=hotpink> Exploratory Data Analysis </font>

## Instructions
    - The data required for this task has been provided in the file 'data.csv'
    - Read the questions provided for each cell and assign your answers to respective variables provided in the following cell.
    - If answers are floating point numbers round of updo two floating point after the decimal
    - For example 10.546 should be read as 10.55, 10.544 as 10.54 and 10.1 as 10.10

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("./datasets/data_weather.csv", parse_dates = ["Day"], dayfirst = True)
df

,Day,Average temperature (°F),Average humidity (%),Average dewpoint (°F),Average barometer (in),Average windspeed (mph),Average gustspeed (mph),Average direction (°deg),Rainfall for month (in),Rainfall for year (in),Maximum rain per minute,Maximum temperature (°F),Minimum temperature (°F),Maximum humidity (%),Minimum humidity (%),Maximum pressure,Minimum pressure,Maximum windspeed (mph),Maximum gust speed (mph),Maximum heat index (°F)
0,2009-01-01,37.8,35,12.7,29.7,26.4,36.8,274,0.00,0.00,0.0,40.1,34.5,44,27,29.762,29.596,41.4,59.0,40.1
1,2009-01-02,43.2,32,14.7,29.5,12.8,18.0,240,0.00,0.00,0.0,52.8,37.5,43,16,29.669,29.268,35.7,51.0,52.8
2,2009-01-03,25.7,60,12.7,29.7,8.3,12.2,290,0.00,0.00,0.0,41.2,6.7,89,35,30.232,29.260,25.3,38.0,41.2
3,2009-01-04,9.3,67,0.1,30.4,2.9,4.5,47,0.00,0.00,0.0,19.4,-0.0,79,35,30.566,30.227,12.7,20.0,32.0
4,2009-01-05,23.5,30,-5.3,29.9,16.7,23.1,265,0.00,0.00,0.0,30.3,15.1,56,13,30.233,29.568,38.0,53.0,32.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3275,2018-10-24,45.9,53,27.5,29.8,2.7,4.6,282,0.85,6.86,0.0,57.3,35.9,81,23,29.947,29.710,12.7,19.6,57.2
3276,2018-10-25,46.7,40,22.7,29.8,4.5,7.2,283,0.85,6.86,0.0,61.8,35.0,60,19,29.933,29.682,13.8,19.6,61.8
3277,2018-10-26,48.4,35,21.6,29.8,9.7,14.4,283,0.85,6.86,0.0,58.7,42.6,48,19,29.979,29.759,20.7,31.1,58.7
3278,2018-10-27,53.3,37,26.6,29.8,10.3,14.8,282,0.85,6.86,0.0,64.5,38.3,78,24,29.935,29.650,28.8,38.0,64.5
3279,2018-10-28,49.4,48,25.2,29.9,5.3,7.6,282,0.85,6.86,0.0,67.3,30.9,90,19,30.040,29.663,18.4,25.3,67.3

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3280 entries, 0 to 3279
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Day                       3280 non-null   datetime64[ns]
 1   Average temperature (°F)  3280 non-null   float64
 2   Average humidity (%)      3280 non-null   int64
 3   Average dewpoint (°F)     3280 non-null   float64
 4   Average barometer (in)    3280 non-null   float64
 5   Average windspeed (mph)   3280 non-null   float64
 6   Average gustspeed (mph)   3280 non-null   float64
 7   Average direction (°deg)  3280 non-null   int64
 8   Rainfall for month (in)   3280 non-null   float64
 9   Rainfall for year (in)    3280 non-null   float64
 10  Maximum rain per minute   3280 non-null   float64
 11  Maximum temperature (°F)  3280 non-null   float64
 12  Minimum temperature (°F)  3280 non-null   float64
 13  Maximum humidity (%)      3280 non-null   int64
 14  Minimum humidity (%)      3280 non-null   int64
 15  Maximum pressure          3280 non-null   float64
 16  Minimum pressure          3280 non-null   float64
 17  Maximum windspeed (mph)   3280 non-null   float64
 18  Maximum gust speed (mph)  3280 non-null   float64
 19  Maximum heat index (°F)   3280 non-null   float64
dtypes: datetime64[ns](1), float64(15), int64(4)
memory usage: 512.6 KB

In [4]:
df.isnull().sum()

Day                         0
Average temperature (°F)    0
Average humidity (%)        0
Average dewpoint (°F)       0
Average barometer (in)      0
Average windspeed (mph)     0
Average gustspeed (mph)     0
Average direction (°deg)    0
Rainfall for month (in)     0
Rainfall for year (in)      0
Maximum rain per minute     0
Maximum temperature (°F)    0
Minimum temperature (°F)    0
Maximum humidity (%)        0
Minimum humidity (%)        0
Maximum pressure            0
Minimum pressure            0
Maximum windspeed (mph)     0
Maximum gust speed (mph)    0
Maximum heat index (°F)     0
dtype: int64

### What is the standard deviation of maximum windspeed across all the days

In [5]:
q1 = df["Maximum windspeed (mph)"].std().round(2)
q1

13.06

### What is the difference between 50th percentile and 75th percentile of average temperature

In [6]:
np.percentile(df["Average temperature (°F)"], [50, 75])

array([45.9, 58.1])

In [7]:
perc_50, perc_75 = np.percentile(df["Average temperature (°F)"], [50, 75])
q2 = round(perc_75 - perc_50, 2)
q2

12.2

### What is the pearson correlation between average dew point and average temperature

In [8]:
corr_dew_temp = df[ ["Average dewpoint (°F)", "Average temperature (°F)"] ].corr().round(2)
corr_dew_temp

                          Average dewpoint (°F)  Average temperature (°F)
Average dewpoint (°F)                      1.00                      0.76
Average temperature (°F)                   0.76                      1.00

In [9]:
q3 = corr_dew_temp.iloc[0, 1]
q3

0.76

### Out of all the available records which month has the lowest average humidity.
    - Assign your answer as month index, for example if its July index is 7

In [10]:
df_day_humidity = df[ ["Day", "Average humidity (%)"] ].nsmallest(1, "Average humidity (%)")
df_day_humidity

            Day  Average humidity (%)
1300 2013-01-22                     9

In [11]:
df_day_humidity.iloc[0, 0]

Timestamp('2013-01-22 00:00:00')

In [12]:
q4 = df_day_humidity.iloc[0, 0].month
q4

1

### Which month has the highest median for maximum_gust_speed out of all the available records. Also find the respective value
    - hint: group by month

In [13]:
grpby_day_maxgust = df[ ["Day", "Maximum gust speed (mph)"]].groupby(by = df["Day"].dt.month)
grpby_day_maxgust

In [14]:
grpby_day_maxgust.median(numeric_only = True)

     Maximum gust speed (mph)
Day
1                        32.2
2                        34.5
3                        31.1
4                        27.6
5                        26.0
6                        26.5
7                        24.2
8                        24.2
9                        24.2
10                       26.5
11                       32.2
12                       33.4

In [15]:
day_gust = grpby_day_maxgust.median(numeric_only = True).nlargest(1, "Maximum gust speed (mph)")
day_gust

     Maximum gust speed (mph)
Day
2                        34.5

In [16]:
q5 = day_gust.index[0]
q5

2

In [17]:
q6 = day_gust.iloc[0, 0]
q6

34.5

###### Determine the average temperature between the months of March 2010 to May 2012 (including both the months)

In [18]:
mask = df["Day"].between(pd.to_datetime("1st March, 2010"), pd.to_datetime("31st May, 2012"))
df[mask]

,Day,Average temperature (°F),Average humidity (%),Average dewpoint (°F),Average barometer (in),Average windspeed (mph),Average gustspeed (mph),Average direction (°deg),Rainfall for month (in),Rainfall for year (in),Maximum rain per minute,Maximum temperature (°F),Minimum temperature (°F),Maximum humidity (%),Minimum humidity (%),Maximum pressure,Minimum pressure,Maximum windspeed (mph),Maximum gust speed (mph),Maximum heat index (°F)
390,2010-03-01,26.1,74,18.4,30.2,2.2,3.4,53,0.02,0.59,0.01,39.1,14.3,90,40,30.375,30.086,15.0,22.0,39.1
391,2010-03-02,27.8,58,12.9,30.2,1.4,2.4,91,0.02,0.59,0.00,48.8,10.5,86,21,30.387,30.012,10.4,14.0,48.8
392,2010-03-03,31.4,56,15.5,30.0,4.5,6.4,315,0.02,0.59,0.00,48.3,15.4,84,23,30.180,29.942,18.4,26.0,48.3
393,2010-03-04,29.9,63,17.9,30.0,1.6,2.9,191,0.02,0.59,0.00,44.6,16.4,83,32,30.138,29.787,6.9,255.0,44.6
394,2010-03-05,29.9,59,16.3,29.9,10.1,14.2,316,0.02,0.59,0.00,36.9,20.0,85,34,29.949,29.693,24.2,36.0,36.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1060,2012-05-27,49.4,19,8.1,29.6,11.7,17.3,241,1.22,2.14,0.00,58.3,42.5,37,10,29.801,29.296,28.8,38.0,58.3
1061,2012-05-28,52.8,23,14.6,29.8,12.6,18.4,245,1.22,2.14,0.00,65.2,43.1,37,10,29.908,29.641,29.9,43.7,71.0
1062,2012-05-29,51.0,35,21.7,29.9,2.3,4.1,318,1.22,2.14,0.00,69.9,30.1,60,12,30.028,29.755,13.8,24.2,75.6
1063,2012-05-30,55.2,39,26.3,29.8,4.4,7.1,286,1.22,2.14,0.00,73.5,34.1,69,13,29.884,29.669,18.4,26.5,76.8
1064,2012-05-31,51.3,55,34.6,29.9,3.0,4.9,59,1.22,2.14,0.00,64.2,34.9,83,33,29.946,29.807,13.8,19.6,64.2

In [19]:
q7 = df[mask].get("Average temperature (°F)").mean().round(2)
q7

45.33

### Find the range of average temperature  on Dec 2010

In [20]:
mask = df["Day"].between(pd.to_datetime("1st Dec, 2010"), pd.to_datetime("31st Dec, 2010"))
df[mask]

,Day,Average temperature (°F),Average humidity (%),Average dewpoint (°F),Average barometer (in),Average windspeed (mph),Average gustspeed (mph),Average direction (°deg),Rainfall for month (in),Rainfall for year (in),Maximum rain per minute,Maximum temperature (°F),Minimum temperature (°F),Maximum humidity (%),Minimum humidity (%),Maximum pressure,Minimum pressure,Maximum windspeed (mph),Maximum gust speed (mph),Maximum heat index (°F)
662,2010-12-02,42.2,39,18.2,30.0,12.6,19.0,310,0.00,12.69,0.00,48.8,36.4,58,28,30.126,29.826,31.1,43.7,48.8
663,2010-12-03,44.8,31,15.9,29.8,13.8,17.1,301,0.00,12.69,0.00,46.2,42.3,41,28,29.851,29.802,31.1,44.9,46.2
664,2010-12-04,31.3,62,18.0,30.2,6.0,7.9,320,0.00,12.69,0.00,46.0,21.8,89,28,30.430,29.828,16.1,20.7,46.0
665,2010-12-05,28.8,67,18.9,30.4,2.7,4.1,68,0.00,12.69,0.00,43.1,18.8,86,45,30.487,30.267,11.5,13.8,43.1
666,2010-12-06,34.3,62,21.4,30.3,4.6,7.0,318,0.00,12.69,0.00,48.1,18.1,87,27,30.465,30.008,17.3,26.5,48.1
667,2010-12-07,34.3,40,12.0,30.2,7.8,11.9,322,0.00,12.69,0.00,46.2,23.0,60,23,30.382,29.951,25.3,34.5,46.2
668,2010-12-08,40.4,26,7.4,30.1,10.6,15.5,308,0.00,12.69,0.00,49.2,23.9,41,15,30.282,29.817,26.5,36.8,49.2
669,2010-12-09,39.6,37,14.9,29.9,15.3,22.5,315,0.00,12.69,0.00,44.0,29.5,57,25,29.998,29.766,34.5,49.5,44.0
670,2010-12-10,35.9,47,17.5,29.8,10.4,16.0,321,0.00,12.69,0.00,43.4,28.1,85,32,29.998,29.645,25.3,38.0,43.4
671,2010-12-11,25.2,41,4.6,30.2,7.2,11.4,329,0.00,12.69,0.00,29.0,17.0,57,31,30.425,29.947,16.1,26.5,29.0
672,2010-12-12,34.8,50,17.4,30.2,10.4,15.5,320,0.00,12.69,0.00,46.7,16.7,66,31,30.425,29.856,28.8,46.0,46.7
673,2010-12-13,45.8,27,13.6,29.9,19.5,28.5,315,0.00,12.69,0.00,53.2,42.6,42,16,29.975,29.770,35.7,57.5,53.2
674,2010-12-14,46.3,26,12.3,29.6,18.5,32.6,314,0.00,12.69,0.00,52.2,42.1,41,18,29.793,29.220,169.1,255.3,52.2
675,2010-12-15,34.1,55,18.5,29.6,10.2,14.7,313,0.01,12.70,0.01,44.3,22.9,88,27,29.942,29.362,27.6,42.6,44.3
676,2010-12-16,20.2,62,8.5,30.1,3.7,6.1,88,0.01,12.70,0.00,29.1,10.5,84,33,30.317,29.936,19.6,29.9,29.1
677,2010-12-17,15.7,73,8.5,30.2,1.7,3.1,111,0.01,12.70,0.00,24.1,10.0,83,53,30.329,30.131,8.1,11.5,24.1
678,2010-12-18,29.7,61,17.5,29.9,6.1,8.9,326,0.01,12.70,0.00,38.9,11.1,83,40,30.166,29.685,19.6,25.3,38.9
679,2010-12-19,36.5,71,27.8,29.6,4.5,6.5,311,0.13,12.82,0.01,41.8,32.3,93,52,29.720,29.418,16.1,21.9,41.8
680,2010-12-20,33.9,83,29.2,29.6,3.0,4.9,88,0.42,13.11,0.01,37.5,28.1,92,54,29.879,29.388,10.4,13.8,37.5
681,2010-12-21,25.0,79,19.3,30.1,2.3,3.6,86,0.49,13.18,0.01,28.7,22.3,87,54,30.318,29.846,8.1,11.5,28.7
682,2010-12-22,25.1,84,20.8,30.3,1.3,1.8,37,0.57,13.26,0.02,39.2,17.7,90,68,30.406,30.072,11.5,16.1,39.2
683,2010-12-23,32.9,71,24.0,30.0,3.1,7.4,341,0.57,13.26,0.00,46.0,19.2,92,44,30.191,29.850,170.2,255.3,46.0
684,2010-12-24,24.4,80,18.7,30.4,1.2,2.1,52,0.58,13.27,0.01,38.2,14.1,89,57,30.598,30.185,6.9,10.4,38.2
685,2010-12-25,24.1,63,10.7,30.5,0.6,1.4,78,0.58,13.27,0.00,51.4,8.4,86,17,30.719,30.255,5.8,10.4,51.4
686,2010-12-26,35.4,40,11.2,30.0,8.1,17.9,325,0.58,13.27,0.00,51.7,16.5,77,15,30.255,29.712,120.8,255.3,51.7
687,2010-12-27,31.4,34,5.9,30.0,14.3,21.2,327,0.58,13.27,0.00,36.9,27.6,50,24,30.177,29.752,27.6,41.4,36.9
688,2010-12-28,31.7,28,1.1,29.9,9.5,13.6,319,0.58,13.27,0.00,41.5,18.0,51,17,30.149,29.592,24.2,32.2,41.5
689,2010-12-29,35.5,37,10.5,29.2,16.1,25.4,315,0.58,13.27,0.00,39.3,32.8,50,15,29.592,29.036,170.2,255.3,39.3
690,2010-12-30,17.5,71,9.3,29.4,3.7,5.7,102,0.58,13.27,0.00,33.4,-1.2,85,44,29.748,29.126,12.7,18.4,33.4
691,2010-12-31,1.5,53,-12.5,30.0,9.9,14.3,319,0.58,13.27,0.00,5.4,-1.4,76,34,30.167,29.735,27.6,40.3,5.4

In [21]:
# np.ptp means peak to peak 

q8 = np.ptp(df[mask].get("Average temperature (°F)")).round(2)
q8

44.8

### Out of all available records which day has the highest difference between maximum_pressure and minimum_pressure
    - assign the date in string format as 'yyyy-mm-dd'. Make sure you enclose it with single quote

In [22]:
maximum_pressure_col_index = -1

for col in df.columns[:]:
    maximum_pressure_col_index += 1
    if col == "Maximum pressure ":
        break

maximum_pressure_col_index

15

In [23]:
pressure_max_min = abs(df["Maximum pressure "]  - df["Minimum pressure "])
pressure_max_min

0       0.166
1       0.401
2       0.972
3       0.339
4       0.665
        ...
3275    0.237
3276    0.251
3277    0.220
3278    0.285
3279    0.377
Length: 3280, dtype: float64

In [24]:
# df.drop(columns = "abs(Max_Pressure - Min_Pressure)", inplace = True)
df.insert(loc = 17, column = "abs(Max_Pressure - Min_Pressure)", value = pressure_max_min)
df

,Day,Average temperature (°F),Average humidity (%),Average dewpoint (°F),Average barometer (in),Average windspeed (mph),Average gustspeed (mph),Average direction (°deg),Rainfall for month (in),Rainfall for year (in),...,Maximum temperature (°F),Minimum temperature (°F),Maximum humidity (%),Minimum humidity (%),Maximum pressure,Minimum pressure,abs(Max_Pressure - Min_Pressure),Maximum windspeed (mph),Maximum gust speed (mph),Maximum heat index (°F)
0,2009-01-01,37.8,35,12.7,29.7,26.4,36.8,274,0.00,0.00,...,40.1,34.5,44,27,29.762,29.596,0.166,41.4,59.0,40.1
1,2009-01-02,43.2,32,14.7,29.5,12.8,18.0,240,0.00,0.00,...,52.8,37.5,43,16,29.669,29.268,0.401,35.7,51.0,52.8
2,2009-01-03,25.7,60,12.7,29.7,8.3,12.2,290,0.00,0.00,...,41.2,6.7,89,35,30.232,29.260,0.972,25.3,38.0,41.2
3,2009-01-04,9.3,67,0.1,30.4,2.9,4.5,47,0.00,0.00,...,19.4,-0.0,79,35,30.566,30.227,0.339,12.7,20.0,32.0
4,2009-01-05,23.5,30,-5.3,29.9,16.7,23.1,265,0.00,0.00,...,30.3,15.1,56,13,30.233,29.568,0.665,38.0,53.0,32.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3275,2018-10-24,45.9,53,27.5,29.8,2.7,4.6,282,0.85,6.86,...,57.3,35.9,81,23,29.947,29.710,0.237,12.7,19.6,57.2
3276,2018-10-25,46.7,40,22.7,29.8,4.5,7.2,283,0.85,6.86,...,61.8,35.0,60,19,29.933,29.682,0.251,13.8,19.6,61.8
3277,2018-10-26,48.4,35,21.6,29.8,9.7,14.4,283,0.85,6.86,...,58.7,42.6,48,19,29.979,29.759,0.220,20.7,31.1,58.7
3278,2018-10-27,53.3,37,26.6,29.8,10.3,14.8,282,0.85,6.86,...,64.5,38.3,78,24,29.935,29.650,0.285,28.8,38.0,64.5
3279,2018-10-28,49.4,48,25.2,29.9,5.3,7.6,282,0.85,6.86,...,67.3,30.9,90,19,30.040,29.663,0.377,18.4,25.3,67.3

In [25]:
df[ ["Day", "abs(Max_Pressure - Min_Pressure)"] ].nlargest(1, "abs(Max_Pressure - Min_Pressure)")

            Day  abs(Max_Pressure - Min_Pressure)
3067 2018-03-23                            16.602

In [26]:
q9 = df[ ["Day", "abs(Max_Pressure - Min_Pressure)"] ].nlargest(1, "abs(Max_Pressure - Min_Pressure)").iloc[0, 0]
str(q9.date())

'2018-03-23'

### How many days falls under median (i.e equal to median value) of barrometer reading.

In [27]:
q10 = sum( df["Average barometer (in)"] == df["Average barometer (in)"].median() )
q10

534

### Out of all the available records how many days are within one standard deviation of average temperature

In [28]:
mean_1 = df["Average temperature (°F)"].mean().round(2)
mean_1

45.16

In [29]:
std_1 = df["Average temperature (°F)"].std().round(2)
std_1

15.19

In [30]:
right_deviated = df["Average temperature (°F)"].round(2) <= (mean_1 + std_1)
left_deviated = df["Average temperature (°F)"].round(2) >= (mean_1 - std_1)

In [31]:
df[right_deviated & left_deviated]

,Day,Average temperature (°F),Average humidity (%),Average dewpoint (°F),Average barometer (in),Average windspeed (mph),Average gustspeed (mph),Average direction (°deg),Rainfall for month (in),Rainfall for year (in),...,Maximum temperature (°F),Minimum temperature (°F),Maximum humidity (%),Minimum humidity (%),Maximum pressure,Minimum pressure,abs(Max_Pressure - Min_Pressure),Maximum windspeed (mph),Maximum gust speed (mph),Maximum heat index (°F)
0,2009-01-01,37.8,35,12.7,29.7,26.4,36.8,274,0.00,0.00,...,40.1,34.5,44,27,29.762,29.596,0.166,41.4,59.0,40.1
1,2009-01-02,43.2,32,14.7,29.5,12.8,18.0,240,0.00,0.00,...,52.8,37.5,43,16,29.669,29.268,0.401,35.7,51.0,52.8
6,2009-01-07,34.2,60,21.6,29.7,20.4,30.0,276,0.00,0.00,...,39.1,27.3,86,46,29.860,29.602,0.258,38.0,54.0,39.1
7,2009-01-08,42.1,41,20.0,29.8,17.5,25.2,265,0.00,0.00,...,51.3,36.9,53,28,29.883,29.627,0.256,35.7,49.0,51.3
8,2009-01-09,30.3,46,11.4,30.0,6.9,10.6,292,0.00,0.00,...,41.5,19.2,82,27,30.446,29.575,0.871,24.2,36.0,41.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3275,2018-10-24,45.9,53,27.5,29.8,2.7,4.6,282,0.85,6.86,...,57.3,35.9,81,23,29.947,29.710,0.237,12.7,19.6,57.2
3276,2018-10-25,46.7,40,22.7,29.8,4.5,7.2,283,0.85,6.86,...,61.8,35.0,60,19,29.933,29.682,0.251,13.8,19.6,61.8
3277,2018-10-26,48.4,35,21.6,29.8,9.7,14.4,283,0.85,6.86,...,58.7,42.6,48,19,29.979,29.759,0.220,20.7,31.1,58.7
3278,2018-10-27,53.3,37,26.6,29.8,10.3,14.8,282,0.85,6.86,...,64.5,38.3,78,24,29.935,29.650,0.285,28.8,38.0,64.5
3279,2018-10-28,49.4,48,25.2,29.9,5.3,7.6,282,0.85,6.86,...,67.3,30.9,90,19,30.040,29.663,0.377,18.4,25.3,67.3

In [32]:
q11 = len( df[right_deviated & left_deviated] )
q11

2092

###### Answers
- q1 = 13.06
- q2 = 12.20
- q3 = 0.76
- q4 = 1
- q5 = 34.50
- q6 = 2
- q7 = 45.33
- q8 = 44.80
- q9 = '2018-03-23'
- q10 = 534
- q11 = 2092